// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRestfulApi.Models;

namespace MyRestfulApi.Migrations
{
    [DbContext(typeof(MyRestfulApiContext))]
    [Migration("20181213141527_useMySqlDb")]
    partial class useMySqlDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("MyRestfulApi.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserGruop");

                    b.Property<string>("UserName");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasData(
                        new { UserID = 1, UserGruop = "admin", UserName = "user1" },
                        new { UserID = 2, UserGruop = "admin", UserName = "user2" },
                        new { UserID = 3, UserGruop = "user", UserName = "user3" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
