// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRestfulApi.Models;

namespace MyRestfulApi.Migrations
{
    [DbContext(typeof(MyRestfulApiContext))]
    partial class MyRestfulApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyRestfulApi.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserGruop");

                    b.Property<string>("UserName");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasData(
                        new { UserID = 1, UserGruop = "admin", UserName = "user1" },
                        new { UserID = 2, UserGruop = "admin", UserName = "user2" },
                        new { UserID = 3, UserGruop = "user", UserName = "user3" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
